package interfaz;

import Conex.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class V_retiro extends javax.swing.JFrame {

    Conexion con1 = new Conexion();
    Connection conet;
    Statement st;
    ResultSet rs;
    //Cuenta
    Integer idCd = V_login.cd;
    Integer idCs = V_login.cs;
    
    //Para comprobación
    boolean respuesta;
    int resultado;
    
    public V_retiro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSoles = new javax.swing.JButton();
        btnDolares = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Retiro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Escoga el tipo de cuenta:");

        btnSoles.setBackground(new java.awt.Color(0, 0, 0));
        btnSoles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSoles.setForeground(new java.awt.Color(255, 255, 255));
        btnSoles.setText("Soles");
        btnSoles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSoles.setMaximumSize(new java.awt.Dimension(72, 53));
        btnSoles.setMinimumSize(new java.awt.Dimension(72, 53));
        btnSoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolesActionPerformed(evt);
            }
        });

        btnDolares.setBackground(new java.awt.Color(0, 0, 0));
        btnDolares.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDolares.setForeground(new java.awt.Color(255, 255, 255));
        btnDolares.setText("Dólares");
        btnDolares.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDolares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDolares.setMaximumSize(new java.awt.Dimension(72, 53));
        btnDolares.setMinimumSize(new java.awt.Dimension(72, 53));
        btnDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDolaresActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(200, 70, 72));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolesActionPerformed
        VerificarCuentaS();
        if (respuesta){
            V_retiro_soles v = new V_retiro_soles();
            v.setVisible(true);
            this.dispose();
        } else {
            Salir();           
        }
    }//GEN-LAST:event_btnSolesActionPerformed

    private void btnDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDolaresActionPerformed
        VerificarCuentaD();
        if (respuesta) {
            V_retiro_dolares v = new V_retiro_dolares();
            v.setVisible(true);
            this.dispose();
        } else {
            Salir();          
        }
    }//GEN-LAST:event_btnDolaresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        resultado = JOptionPane.showConfirmDialog(null, "Desea cancelar?", "Confirmar operación", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        System.out.println(resultado);
        
        if(resultado==0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_retiro().setVisible(true);
            }
        });
    }
    
    void Salir() {
        JOptionPane.showMessageDialog(null,"Usted no posee este tipo de cuenta");
        V_home v = new V_home();
        v.setVisible(true);
        this.dispose();
    }
    
    boolean VerificarCuentaD() {
        String sqlDolar= "SELECT salCueDol FROM tcuentadolar WHERE idCueDol="+idCd+";";
        
            try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs=st.executeQuery(sqlDolar);
            
            try {
                //Verificar cuenta
                if(rs.next()) {
                    respuesta=true;
                } else {
                    respuesta=false;
                    rs.close();
                }
            } catch (Exception e) {
                System.err.println("No se puedo establecer conexión con la base de datos. Error: " + e);
                JOptionPane.showMessageDialog(this, "Error, intente de nuevo más tarde");
            }
            } catch(Exception e) {
                
            }
            return respuesta;
    }
    
    boolean VerificarCuentaS() {
        String sqlSol= "SELECT salCueSol FROM tcuentasol WHERE idCueSol="+idCs+";";
            
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs=st.executeQuery(sqlSol);
            
        try {
                //Verificar cuenta
                if(rs.next()) {
                    respuesta=true;
                } else {
                    //rs.close();
                    respuesta=false;
                }
        } catch (Exception e) {
                System.err.println("No se puedo establecer conexión con la base de datos. Error: " + e);
                JOptionPane.showMessageDialog(this, "Error, intente de nuevo más tarde");
            }
        } catch(Exception e) {
                
            }
        return respuesta;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDolares;
    private javax.swing.JButton btnSoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
